### ISSUE TITLE
nn model fit params are not used

### ISSUE THREAD

**Issue by krsnapaudel** [BigDataWUR/AgML-CY-Bench#266] opened 2024-07-05 07:25 UTC
Fit parameters, e.g. batch size and number of epochs, passed to `fit` are ignored. The call to `train_model` must use the params passed.

**Comment by aikepotze** [comment] 2024-07-05 12:51
Could not reproduce bug. Changing fit parameters for LSTM produced expected results in multiple tests.
Closing issue for now, will reopen if bug is encountered again.

**Closed by aikepotze** 2024-07-05 12:51 UTC
Labels: bug, model-api
